version: '3.9'
services:
  food-review:
    build: food-review
    ports:
      - '3000:3000'
  reviews:
    build: reviews
    ports:
      - '4001:4001'
  event-bus:
    build: event-bus
  photos:
    build: photos
    ports:
      - '4000:4000'
  management:
    build: management
    ports:
      - '4002:4002'